VIETLIKE/Controllers/Tour/TourOtherTabController.cs
using CRM.Core;
using CRM.Infrastructure;
using VIETLIKE.Models;
using VIETLIKE.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace VIETLIKE.Controllers.Tour
{
    [Authorize]
    public class TourOtherTabController : BaseController
    {
        // GET: TourOtherTab
        #region Init
        private IGenericRepository<tbl_LiabilityCustomer> _liabilityCustomerRepository;
        private IGenericRepository<tbl_Program> _programRepository;
        private IGenericRepository<tbl_LiabilityPartner> _liabilityPartnerRepository;
        private IGenericRepository<tbl_ReviewTour> _reviewTourRepository;
        private IGenericRepository<tbl_ReviewTourDetail> _reviewTourDetailRepository;
        private IGenericRepository<tbl_Contract> _contractRepository;
        private IGenericRepository<tbl_Staff> _staffRepository;
        private IGenericRepository<tbl_Customer> _customerRepository;
        private IGenericRepository<tbl_Partner> _partnerRepository;
        private IGenericRepository<tbl_Tags> _tagsRepository;
        private IGenericRepository<tbl_Task> _taskRepository;
        private IGenericRepository<tbl_CustomerContact> _customerContactRepository;
        private IGenericRepository<tbl_CustomerVisa> _customerVisaRepository;
        private IGenericRepository<tbl_CustomerContactVisa> _customerContactVisaRepository;
        private IGenericRepository<tbl_TaskStaff> _taskStaffRepository;
        private IGenericRepository<tbl_Dictionary> _dictionaryRepository;
        private IGenericRepository<tbl_DocumentFile> _documentFileRepository;
        private IGenericRepository<tbl_UpdateHistory> _updateHistoryRepository;
        private IGenericRepository<tbl_ContactHistory> _contactHistoryRepository;
        private IGenericRepository<tbl_AppointmentHistory> _appointmentHistoryRepository;
        private IGenericRepository<tbl_Tour> _tourRepository;
        private IGenericRepository<tbl_TourGuide> _tourGuideRepository;
        private IGenericRepository<tbl_ServicesPartner> _servicesPartnerRepository;
        private IGenericRepository<tbl_TourCustomerVisa> _tourCustomerVisaRepository;
        private IGenericRepository<tbl_Quotation> _quotationRepository;
        private IGenericRepository<tbl_TourSchedule> _tourScheduleRepository;
        private IGenericRepository<tbl_TourCustomer> _tourCustomerRepository;
        private DataContext _db;

        public TourOtherTabController(
            IGenericRepository<tbl_LiabilityCustomer> liabilityCustomerRepository,
            IGenericRepository<tbl_LiabilityPartner> liabilityPartnerRepository,
            IGenericRepository<tbl_Program> programRepository,
            IGenericRepository<tbl_ReviewTour> reviewTourRepository,
            IGenericRepository<tbl_ReviewTourDetail> reviewTourDetailRepository,
            IGenericRepository<tbl_Contract> contractRepository,
            IGenericRepository<tbl_Partner> partnerRepository,
            IGenericRepository<tbl_Staff> staffRepository,
            IGenericRepository<tbl_Customer> customerRepository,
            IGenericRepository<tbl_Tags> tagsRepository,
            IGenericRepository<tbl_Task> taskRepository,
            IGenericRepository<tbl_CustomerContact> customerContactRepository,
            IGenericRepository<tbl_CustomerVisa> customerVisaRepository,
            IGenericRepository<tbl_TaskStaff> taskStaffRepository,
            IGenericRepository<tbl_Dictionary> dictionaryRepository,
            IGenericRepository<tbl_CustomerContactVisa> customerContactVisaRepository,
            IGenericRepository<tbl_DocumentFile> documentFileRepository,
            IGenericRepository<tbl_UpdateHistory> updateHistoryRepository,
            IGenericRepository<tbl_ContactHistory> contactHistoryRepository,
            IGenericRepository<tbl_AppointmentHistory> appointmentHistoryRepository,
            IGenericRepository<tbl_Tour> tourRepository,
            IGenericRepository<tbl_TourGuide> tourGuideRepository,
            IGenericRepository<tbl_ServicesPartner> servicesPartnerRepository,
            IGenericRepository<tbl_TourCustomerVisa> tourCustomerVisaRepository,
            IGenericRepository<tbl_Quotation> quotationRepository,
            IGenericRepository<tbl_TourSchedule> tourScheduleRepository,
            IGenericRepository<tbl_TourCustomer> tourCustomerRepository,
            IBaseRepository baseRepository)
            : base(baseRepository)
        {
            this._liabilityCustomerRepository = liabilityCustomerRepository;
            this._liabilityPartnerRepository = liabilityPartnerRepository;
            this._programRepository = programRepository;
            this._reviewTourRepository = reviewTourRepository;
            this._reviewTourDetailRepository = reviewTourDetailRepository;
            this._partnerRepository = partnerRepository;
            this._contractRepository = contractRepository;
            this._customerRepository = customerRepository;
            this._customerContactRepository = customerContactRepository;
            this._tagsRepository = tagsRepository;
            this._taskRepository = taskRepository;
            this._customerVisaRepository = customerVisaRepository;
            this._customerContactVisaRepository = customerContactVisaRepository;
            this._taskStaffRepository = taskStaffRepository;
            this._dictionaryRepository = dictionaryRepository;
            this._documentFileRepository = documentFileRepository;
            this._contactHistoryRepository = contactHistoryRepository;
            this._appointmentHistoryRepository = appointmentHistoryRepository;
            this._updateHistoryRepository = updateHistoryRepository;
            this._staffRepository = staffRepository;
            this._tourRepository = tourRepository;
            this._tourGuideRepository = tourGuideRepository;
            this._servicesPartnerRepository = servicesPartnerRepository;
            this._tourCustomerVisaRepository = tourCustomerVisaRepository;
            this._quotationRepository = quotationRepository;
            this._tourScheduleRepository = tourScheduleRepository;
            this._tourCustomerRepository = tourCustomerRepository;
            _db = new DataContext();
        }

        #endregion

        #region Permission
        void Permission(int PermissionsId, int formId)
        {
            var list = _db.tbl_ActionData.Where(p => p.FormId == formId & p.PermissionsId == PermissionsId).Select(p => p.FunctionId).ToList();
            ViewBag.IsAdd = list.Contains(1);
            ViewBag.IsEdit = list.Contains(3);
            ViewBag.IsDelete = list.Contains(2);
            ViewBag.IsImport = list.Contains(4);
        }
        #endregion

        #region Lịch hẹn
        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> CreateAppointment(tbl_AppointmentHistory model, FormCollection form)
        {
            try
            {
                Permission(clsPermission.GetUser().PermissionID, 87);
                model.TourId = Convert.ToInt32(Session["idTour"].ToString());
                model.CreatedDate = DateTime.Now;
                model.ModifiedDate = DateTime.Now;
                model.OtherStaff = form["OtherStaff"];
                model.StaffId = clsPermission.GetUser().StaffID;
                model.PartnerId = model.PartnerId == 0 ? null : model.PartnerId;

                if (await _appointmentHistoryRepository.Create(model))
                {
                    UpdateHistory.SaveHistory(87, "Thêm mới lịch hẹn " + model.Title,
                        model.Id, //appointment
                        model.ContractId, //contract
                        model.CustomerId, //customer
                        model.PartnerId, //partner
                        model.ProgramId, //program
                        model.TaskId, //task
                        model.TourId, //tour
                        null, //quotation
                        null, //document
                        null, //history
                        null // ticket
                        );

                    var list = _appointmentHistoryRepository.GetAllAsQueryable().AsEnumerable()
                            .Where(p => p.TourId == model.TourId).Where(p => p.IsDelete == false)
                            .OrderByDescending(p => p.CreatedDate)
                            .Select(p => new tbl_AppointmentHistory
                            {
                                Id = p.Id,
                                Title = p.Title,
                                Time = p.Time,
                                StatusId = p.StatusId,
                                tbl_DictionaryStatus = _dictionaryRepository.FindId(p.StatusId),
                                tbl_Staff = _staffRepository.FindId(p.StaffId),
                                Note = p.Note,
                                OtherStaff = p.OtherStaff
                            }).ToList();
                    return PartialView("~/Views/TourTabInfo/_LichHen.cshtml", list);
                }
                else
                {
                    return PartialView("~/Views/TourTabInfo/_LichHen.cshtml");
                }
            }
            catch
            {
                return PartialView("~/Views/TourTabInfo/_LichHen.cshtml");
            }
        }

        public JsonResult LoadPartner(int id)
        {
            var model = new SelectList(_partnerRepository.GetAllAsQueryable().Where(p => p.DictionaryId == id && p.IsDelete == false).ToList(), "Id", "Name");
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadServicePartner(int id)
        {
            var model = new SelectList(_servicesPartnerRepository.GetAllAsQueryable().Where(p => p.PartnerId == id && p.IsDelete == false).ToList(), "Id", "Name");

VIETLIKE/Views/TourOtherTab/_Partial_EditAppointmentHistory.cshtml
@using VIETLIKE.Utilities
@model CRM.Core.tbl_AppointmentHistory

<div class="modal fade  bs-modal-lg" id="modal-edit-appointment" role="document" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Lịch hẹn</h4>
            </div>
            @using (Ajax.BeginForm("UpdateAppointment", "TourOtherTab", null, new AjaxOptions { OnFailure = "OnFailureTourTab", OnSuccess = "OnSuccessTourTab", UpdateTargetId = "lichhen" }))
            {
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.StaffId)
                @Html.HiddenFor(model => model.TourId)
                @Html.HiddenFor(model => model.CreatedDate)
                
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-md-3">Tiêu đề</label>
                                    <div class="col-lg-9 col-md-9">
                                        @Html.TextBoxFor(model => model.Title, new { @class = "form-control",  })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-md-3">Chương trình</label>
                                    <div class="col-lg-9 col-md-9">
                                        <select class="form-control" id="edit-program-lichhen" name="ProgramId" style="width: 100%">
                                            <option>-- Chọn chương trình --</option>
                                            @foreach (var item in LoadData.ProgramList())
                                            {
                                                <option value="@item.Id" @(Model != null && Model.ProgramId == item.Id ? "selected" : "")>[@item.Code] @item.Name</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-md-3">Nhiệm vụ</label>
                                    <div class="col-lg-3 col-md-3">
                                        <select class="form-control" id="edit-task-lichhen" name="TaskId" style="width: 100%">
                                            <option>-- Chọn nhiệm vụ --</option>
                                            @foreach (var item in LoadData.TaskList())
                                            {
                                                <option value="@item.Id" @(Model != null && Model.TaskId == item.Id ? "selected" : "")>[@item.Code] @item.Name</option>
                                            }
                                        </select>
                                    </div>
                                    <label class="control-label col-lg-3 col-md-3">Trạng thái</label>
                                    <div class="col-lg-3 col-md-3">
                                        <select class="form-control" id="edit-status-lichhen" name="StatusId" style="width: 100%" >
                                            @foreach (var item in LoadData.StatusProcessList())
                                            {
                                                <option value="@item.Id" @(Model != null && Model.StatusId == item.Id ? "selected" : "")>@item.Name</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-md-3">Dịch vụ</label>
                                    <div class="col-lg-3 col-md-3">
                                        <select class="form-control" id="edit-service-lichhen" name="ServiceId" style="width: 100%">
                                            <option>-- Chọn dịch vụ --</option>
                                            @foreach (var item in LoadData.ServiceList())
                                            {
                                                <option value="@item.Id" @(Model != null && Model.ServiceId == item.Id ? "selected" : "")>@item.Name</option>
                                            }
                                        </select>
                                    </div>
                                    <label class="control-label col-lg-3 col-md-3">Đối tác</label>
                                    <div class="col-lg-3 col-md-3">
                                        <select class="form-control" id="edit-partner-lichhen" name="PartnerId" style="width: 100%">
                                            @foreach (var item in LoadData.PartnerList(Model.ServiceId ?? 0))
                                            {
                                                <option value="@item.Id" @(Model != null && Model.PartnerId == item.Id ? "selected" : "")>@item.Name</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-md-3">Nhân viên khác</label>
                                    <div class="col-lg-9 col-md-9">
                                        <select class="form-control" id="edit-staff-customer" multiple style="width: 100%" name="OtherStaff">
                                            @foreach (var item in LoadData.StaffList())
                                            {
                                                <option value="@item.Id" @(Model.OtherStaff != null && Model.OtherStaff.Contains(item.Id.ToString()) ? "selected" : "")>[@item.Code] @item.FullName</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-md-3">Diễn giải</label>
                                    <div class="col-lg-9 col-md-9">
                                        @Html.TextAreaFor(model => model.Note, new { @class = "form-control", id = "edit-note-lichhen" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-md-3">Loại lịch hẹn</label>
                                    <div class="col-lg-3 col-md-3">
                                        <select class="form-control" id="edit-type-lichhen" name="DictionaryId" style="width: 100%" >
                                            @foreach (var item in LoadData.AppointmentTypeList())
                                            {
                                                <option value="@item.Id" @(Model != null && Model.DictionaryId == item.Id ? "selected" : "")>@item.Name</option>
                                            }
                                        </select>
                                    </div>
                                    <label class="control-label col-lg-3 col-md-3">Ngày hẹn</label>
                                    <div class="col-lg-3 col-md-3">
                                        @Html.TextBoxFor(model => model.Time, "{0:s}", new { @class = "form-control", @type = "datetime-local", id = "edit-ngayhen-lichhen", required = "required" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-3 col-md-3">
                                        @Html.CheckBoxFor(model => model.IsNotify, new { id = "edit-check-notify" })&nbsp;Nhắc trước
                                    </label>
                                    <div class="col-lg-3 col-md-3">
                                        <select class="form-control" id="edit-nhactruoc-lichhen" name="Notify" disabled="@(Model != null && Model.IsNotify == true ? "" : "disabled")">
                                            <option value="5" @(Model != null && Model.Notify == 5 ? "selected" :"")>5 phút</option>
                                            <option value="10" @(Model != null && Model.Notify == 10 ? "selected" : "")>10 phút</option>
                                            <option value="15" @(Model != null && Model.Notify == 15 ? "selected" : "")>15 phút</option>
                                            <option value="20" @(Model != null && Model.Notify == 20 ? "selected" : "")>20 phút</option>
                                            <option value="25" @(Model != null && Model.Notify == 25 ? "selected" : "")>25 phút</option>
                                            <option value="30" @(Model != null && Model.Notify == 30 ? "selected" : "")>30 phút</option>
                                        </select>
                                    </div>
                                    <label class="control-label col-lg-3 col-md-3">
                                        @Html.CheckBoxFor(model => model.IsRepeat, new { id = "edit-check-repeat" })&nbsp;Lặp lại
                                    </label>
                                    <div class="col-lg-3 col-md-3">
                                        <select class="form-control" id="edit-laplai-lichhen" name="Repeat" disabled="@(Model != null && Model.IsRepeat == true ? "" : "disabled")">
                                            <option value="5" @(Model != null && Model.Repeat == 5 ? "selected" : "")>5 phút</option>
                                            <option value="10" @(Model != null && Model.Repeat == 10 ? "selected" : "")>10 phút</option>
                                            <option value="15" @(Model != null && Model.Repeat == 15 ? "selected" : "")>15 phút</option>
                                            <option value="20" @(Model != null && Model.Repeat == 20 ? "selected" : "")>20 phút</option>
                                            <option value="25" @(Model != null && Model.Repeat == 25 ? "selected" : "")>25 phút</option>
                                            <option value="30" @(Model != null && Model.Repeat == 30 ? "selected" : "")>30 phút</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div align="center" style="margin-bottom: 20px">
                    <button type="submit" class="btn blue">Lưu</button>
                    <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
                </div>
            }
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

VIETLIKE/Views/TourOtherTab/_Partial_EditCongNoKhachHang.cshtml
@using VIETLIKE.Utilities
@model CRM.Core.tbl_LiabilityCustomer

<div class="modal fade" id="modal-edit-congnokh" role="document" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Thêm công nợ của khách hàng</h4>
            </div>
            @using (Ajax.BeginForm("UpdateLiabilityCustomer", "TourOtherTab", null, new AjaxOptions { OnFailure = "OnFailureTourTab", OnSuccess = "OnSuccessCNKH", UpdateTargetId = "congnokh" }))
            {
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.TourId)
                @Html.HiddenFor(model => model.CreateDate)
                @Html.HiddenFor(model => model.CustomerId)
                @Html.HiddenFor(model => model.StaffId)

                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Tổng giá trị hợp đồng</label>
                                    <div class="col-lg-6 col-md-6">
                                        @Html.TextBoxFor(model => model.TotalContract@*, "{0:0,0}"*@, new { @class = "form-control Ecnkh", id = "EcnkhTong" })
                                    </div>
                                    <div class="col-lg-2 col-md-2">
                                        <select class="form-control" name="CurrencyId" id="edit-currency-congnokh" style="width: 100%">
                                            @foreach (var item in LoadData.CurrencyList())
                                            {
                                                <option value="@item.Id" @(Model != null && Model.CurrencyId == item.Id ? "selected" : "")>@item.Name</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Thanh toán đợt 1</label>
                                    <div class="col-lg-4 col-md-4">
                                        @Html.TextBoxFor(model => model.FirstPrice, @*"{0:0,0}",*@ new { @class = "form-control Ecnkh", id = "EcnkhDot1" })
                                    </div>
                                    <label class="control-label col-lg-1 col-md-1">Ngày</label>
                                    <div class="col-lg-3 col-md-3">
                                            @Html.TextBoxFor(model => model.FirstDate, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Thanh toán đợt 2</label>
                                    <div class="col-lg-4 col-md-4">
                                        @Html.TextBoxFor(model => model.SecondPrice, @*"{0:0,0}",*@ new { @class = "form-control Ecnkh", id = "EcnkhDot2" })
                                    </div>
                                    <label class="control-label col-lg-1 col-md-1">Ngày</label>
                                    <div class="col-lg-3 col-md-3">
                                            @Html.TextBoxFor(model => model.SecondDate, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Thanh toán đợt 3</label>
                                    <div class="col-lg-4 col-md-4">
                                        @Html.TextBoxFor(model => model.ThirdPrice, @*"{0:0,0}",*@ new { @class = "form-control Ecnkh", id = "EcnkhDot3" })
                                    </div>
                                    <label class="control-label col-lg-1 col-md-1">Ngày</label>
                                    <div class="col-lg-3 col-md-3">
                                            @Html.TextBoxFor(model => model.ThirdDate, "{0:yyyy-MM-dd}", new { @class = "form-control", type = "date" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Tổng giá trị thanh lý</label>
                                    <div class="col-lg-8 col-md-8">
                                        @Html.TextBoxFor(model => model.TotalLiquidation, @*"{0:0,0}",*@ new { @class = "form-control Ecnkh", id = "EcnkhTongThanhLy" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Tổng giá trị còn lại</label>
                                    <div class="col-lg-8 col-md-8">
                                        @Html.TextBoxFor(model => model.TotalRemaining, @*"{0:0,0}",*@ new { @class = "form-control Ecnkh", id="EcnkhTongConLai" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Đã thanh toán</label>
                                    <div class="col-lg-8 col-md-8">
                                        @Html.CheckBoxFor(model => model.IsPayment)
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-4 col-md-4">Ghi chú</label>
                                    <div class="col-lg-8 col-md-8">
                                        @Html.TextAreaFor(model => model.Note, new { @class = "form-control", id = "edit-note-liabilitycustomer" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div align="center" style="margin-bottom: 20px">
                    <button type="submit" class="btn blue">Lưu</button>
                    <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
                </div>
            }
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>