VIETLIKE/Controllers/PromotionManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VIETLIKE.Controllers
{
    public class PromotionManageController : Controller
    {
        //
        // GET: /PromotionManage/

        public ActionResult Index()
        {
            return View();
        }

    }
}

VIETLIKE/Views/PromotionManage/Index.cshtml
@{
    ViewBag.Title = "Quản lý Chương trình khuyến mãi";
}

<div class="page-content">
    <!-- BEGIN PAGE HEAD-->
    <div class="page-head">
        <!-- BEGIN PAGE TITLE -->
        <div class="page-title">
            <h1>DANH SÁCH CHƯƠNG TRÌNH KHUYẾN MÃI</h1>
        </div>
        <!-- END PAGE TITLE -->

    </div>
    <!-- END PAGE HEAD-->
    <!-- BEGIN PAGE BREADCRUMB -->
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="/">Trang chủ</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">Page Layouts</span>
        </li>
    </ul>
    <!-- END PAGE BREADCRUMB -->
    <!-- BEGIN PAGE BASE CONTENT -->
    <div class="note note-info">
        <div class="row">
            <div class="col-md-4">
                <label>Chi nhánh</label>
                <select class="form-control" id="nhanvien-lichhen">
                    <option>Chi nhánh VIETLIKE Sài Gòn</option>
                    <option>Chi nhánh VIETLIKE Hà Nội</option>
                </select>
            </div>
            <div class="col-md-4">
                <label>Từ ngày</label>
                <div class="input-group" data-date-format="mm/dd/yyyy">
                    <input type="date" class="form-control" id="tungay-lichhen">
                </div>
            </div>
            <div class="col-md-4">
                <label>Đến ngày</label>
                <div class="input-group" data-date-format="mm/dd/yyyy">
                    <input type="date" class="form-control" id="denngay-lichhen">
                </div>
            </div>
            <div class="col-md-12 margintop10">
                <a class="btn btn-default" href="@Url.Action("Index", "PromotionManage")"><i class="fa fa-refresh"></i>&nbsp;Nạp</a>
                <button class="btn btn-primary" id="btnAdd" href="#modal-insert-promotion" data-toggle="modal"><i class="fa fa-plus"></i>&nbsp;Thêm</button>
                <button class="btn btn-warning" id="btnEdit" href="#modal-edit-promotion" data-toggle="modal"><i class="fa fa-pencil"></i>&nbsp;Sửa</button>
                <button class="btn btn-danger" id="btnRemove"><i class="fa fa-remove"></i>&nbsp;Xóa</button>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="portlet light bordered">
                <div class="portlet-body">
                    <div class="table-scrollable table-custom-format">
                        <table class="table table-striped table-bordered table-hover" id="">
                            <thead>
                                <tr>
                                    <th class="table-checkbox">
                                        <input type="checkbox" id="allcb" name="allcb" onclick="SelectAllCb()" />
                                    </th>
                                    <th>STT</th>
                                    <th>Tên chương trình</th>
                                    <th>Chiến dịch</th>
                                    <th>Tour</th>
                                    <th>Từ ngày</th>
                                    <th>Đến ngày</th>
                                    <th>Hết hạn</th>
                                    <th>Diễn giải</th>
                                    <th>Ngày nhập</th>
                                    <th>Người nhập</th>
                                </tr>
                            </thead>
                            <tbody>
                                @for (int i = 0; i < 5; i++)
                                {
                                    <tr class="odd gradeX">
                                        <td class="width24">
                                            <input type="checkbox" id="cb@(i)" name="cb@(i)" onclick="CheckSelect()" />
                                        </td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="portlet light bordered">
                <div class="portlet-body">
                    <div class="tabbable-custom ">
                        <ul class="nav nav-tabs ">
                            <li class="active">
                                <a href="#tab1" data-toggle="tab">Chi tiết</a>
                            </li>
                            <li>
                                <a href="#tab2" data-toggle="tab">Tour</a>
                            </li>
                            <li>
                                <a href="#tab3" data-toggle="tab">Nhóm khách hàng</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab1">
                                @*Chi tiết tour*@
                                <div class="table-scrollable table-custom-format">
                                    <table class="table table-striped table-bordered table-hover" id="">
                                        <thead>
                                            <tr>
                                                <th>STT</th>
                                                <th>Giải thưởng</th>
                                                <th>Người nhận</th>
                                                <th>Mã người nhận</th>
                                                <th>Hiệu lực</th>
                                                <th>Ghi chú</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="tab-pane" id="tab2">
                                @*Tour*@
                                <div class="table-scrollable table-custom-format">
                                    <table class="table table-striped table-bordered table-hover" id="">
                                        <thead>
                                            <tr>
                                                <th>STT</th>
                                                <th>Mã tour</th>
                                                <th>Tên tour</th>
                                                <th>Thời gian</th>
                                                <th>Tình trạng</th>
                                                <th>Ghi chú</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="tab-pane" id="tab3">
                                @*Nhóm khách hàng*@
                                <div class="table-scrollable table-custom-format">
                                    <table class="table table-striped table-bordered table-hover" id="">
                                        <thead>
                                            <tr>
                                                <th>STT</th>
                                                <th>Nhóm khách hàng</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td></td>
                                                <td></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END PAGE BASE CONTENT -->
</div>

@Html.Partial("_Partial_InsertPromotion")
@Html.Partial("_Partial_EditPromotion")

@section scripts{
<script src="~/Content/ckeditor-basic/ckeditor.js"></script>
    <script>
        CKEDITOR.replace("insert-promotion");
        CKEDITOR.replace("edit-promotion");
    </script>
}

VIETLIKE/Views/PromotionManage/_Partial_EditPromotion.cshtml
<div class="modal fade  bs-modal-lg" id="modal-edit-promotion" role="document" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Chương trình khuyến mãi</h4>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="control-label col-lg-3 col-md-3">Tên chương trình</label>
                                <div class="col-lg-9 col-md-9">
                                    <input type="text" value="" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-lg-3 col-md-3">Tour</label>
                                <div class="col-lg-9 col-md-9">
                                    <select class="form-control" id="edit-tour-promotion" multiple="multiple" style="width: 100%">
                                        <option>1--------</option>
                                        <option>2--------</option>
                                        <option>3--------</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-lg-3 col-md-3">Chiến dịch</label>
                                <div class="col-lg-9 col-md-9">
                                    <select class="form-control" id="edit-program-promotion" multiple="multiple" style="width: 100%">
                                        <option>1--------</option>
                                        <option>2--------</option>
                                        <option>3--------</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-lg-3 col-md-3">Loại khách hàng</label>
                                <div class="col-lg-3 col-md-3">
                                   <select class="form-control" id="edit-customertype-promotion" style="width: 100%">
                                        <option>--------</option>
                                    </select>
                                </div>
                                <label class="control-label col-lg-3 col-md-3">Loại thẻ</label>
                                <div class="col-lg-3 col-md-3">
                                    <select class="form-control" id="edit-membercard-promotion" style="width: 100%">
                                        <option>--------</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-lg-3 col-md-3">Giải thưởng</label>
                                <div class="col-lg-9 col-md-9">
                                    <input class="form-control" value="" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-lg-3 col-md-3">Diễn giải</label>
                                <div class="col-lg-9 col-md-9">
                                    <textarea class="form-control" name="edit-promotion"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div align="center" style="margin-bottom: 20px">
                <button type="button" class="btn blue" id="btnLuuThem">Lưu</button>
                <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

VIETLIKE/Views/PromotionManage/_Partial_InsertPromotion.cshtml
<div class="modal fade  bs-modal-lg" id="modal-insert-promotion" role="document" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Chương trình khuyến mãi</h4>
            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="control-label col-lg-3 col-md-3">Tên chương trình</label>
                                <div class="col-lg-9 col-md-9">
                                    <input type="text" value="" class="form-control" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-lg-3 col-md-3">Tour</label>
                                <div class="col-lg-9 col-md-9">
                                    <select class="form-control" id="insert-tour-promotion" multiple="multiple" style="width: 100%">
                                        <option>1--------</option>
                                        <option>2--------</option>
                                        <option>3--------</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-lg-3 col-md-3">Chiến dịch</label>
                                <div class="col-lg-9 col-md-9">
                                    <select class="form-control" id="insert-program-promotion" multiple="multiple" style="width: 100%">
                                        <option>1--------</option>
                                        <option>2--------</option>
                                        <option>3--------</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-lg-3 col-md-3">Loại khách hàng</label>
                                <div class="col-lg-3 col-md-3">
                                   <select class="form-control" id="insert-customertype-promotion" style="width: 100%">
                                        <option>--------</option>
                                    </select>
                                </div>
                                <label class="control-label col-lg-3 col-md-3">Loại thẻ</label>
                                <div class="col-lg-3 col-md-3">
                                    <select class="form-control" id="insert-membercard-promotion" style="width: 100%">
                                        <option>--------</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-lg-3 col-md-3">Giải thưởng</label>
                                <div class="col-lg-9 col-md-9">
                                    <input class="form-control" value="" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-lg-3 col-md-3">Diễn giải</label>
                                <div class="col-lg-9 col-md-9">
                                    <textarea class="form-control" name="insert-promotion"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div align="center" style="margin-bottom: 20px">
                <button type="button" class="btn blue" id="btnLuuThem">Lưu</button>
                <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>