VIETLIKE/Controllers/Report/HistoryLogReportController.cs
using CRM.Core;
using CRM.Infrastructure;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using VIETLIKE.Models;
using VIETLIKE.Utilities;

namespace VIETLIKE.Controllers.Report
{
    public class HistoryLogReportController : BaseController
    {
        // GET: HistoryLogReport

        #region Init

        private IGenericRepository<tbl_Dictionary> _dictionaryRepository;
        private IGenericRepository<tbl_ServicesPartner> _servicesPartnerRepository;
        private IGenericRepository<tbl_Tour> _tourRepository;
        private IGenericRepository<tbl_ReviewTour> _reviewTourRepository;
        private IGenericRepository<tbl_ReviewTourDetail> _reviewTourDetailRepository;
        private IGenericRepository<tbl_Customer> _customerRepository;
        private IGenericRepository<tbl_CustomerVisa> _customerVisaRepository;
        private IGenericRepository<tbl_Tags> _tagsRepository;
        private IGenericRepository<tbl_Task> _taskRepository;
        private IGenericRepository<tbl_DocumentFile> _documentFileRepository;
        private IGenericRepository<tbl_AppointmentHistory> _appointmentHistoryRepository;
        private IGenericRepository<tbl_ContactHistory> _contactHistoryRepository;
        private IGenericRepository<tbl_Contract> _contractRepository;
        private IGenericRepository<tbl_Partner> _partnerRepository;
        private IGenericRepository<tbl_TourGuide> _tourGuideRepository;
        private IGenericRepository<tbl_TourSchedule> _tourScheduleRepository;
        private IGenericRepository<tbl_TourCustomer> _tourCustomerRepository;
        private IGenericRepository<tbl_TourCustomerVisa> _tourCustomerVisaRepository;
        private IGenericRepository<tbl_TourOption> _tourOptionRepository;
        private IGenericRepository<tbl_Staff> _staffRepository;
        private IGenericRepository<tbl_LiabilityCustomer> _liabilityCustomerRepository;
        private IGenericRepository<tbl_LiabilityPartner> _liabilityPartnerRepository;
        private IGenericRepository<tbl_CustomerContact> _customerContactRepository;
        private IGenericRepository<tbl_CustomerContactVisa> _customerContactVisaRepository;
        private IGenericRepository<tbl_UpdateHistory> _updateHistoryRepository;
        private IGenericRepository<tbl_Form> _formRepository;
        private IGenericRepository<tbl_Module> _moduleRepository;
        private DataContext _db;

        public HistoryLogReportController(IGenericRepository<tbl_Dictionary> dictionaryRepository,
            IGenericRepository<tbl_ServicesPartner> servicesPartnerRepository,
            IGenericRepository<tbl_Tour> tourRepository,
            IGenericRepository<tbl_ReviewTour> reviewTourRepository,
            IGenericRepository<tbl_ReviewTourDetail> reviewTourDetailRepository,
            IGenericRepository<tbl_Customer> customerRepository,
            IGenericRepository<tbl_CustomerVisa> customerVisaRepository,
            IGenericRepository<tbl_Tags> tagsRepository,
            IGenericRepository<tbl_Task> taskRepository,
            IGenericRepository<tbl_DocumentFile> documentFileRepository,
            IGenericRepository<tbl_AppointmentHistory> appointmentHistoryRepository,
            IGenericRepository<tbl_ContactHistory> contactHistoryRepository,
            IGenericRepository<tbl_Contract> contractRepository,
            IGenericRepository<tbl_Partner> partnerRepository,
            IGenericRepository<tbl_TourGuide> tourGuideRepository,
            IGenericRepository<tbl_TourSchedule> tourScheduleRepository,
            IGenericRepository<tbl_TourCustomer> tourCustomerRepository,
            IGenericRepository<tbl_TourCustomerVisa> tourCustomerVisaRepository,
            IGenericRepository<tbl_TourOption> tourOptionRepository,
            IGenericRepository<tbl_Staff> staffRepository,
            IGenericRepository<tbl_LiabilityCustomer> liabilityCustomerRepository,
            IGenericRepository<tbl_LiabilityPartner> liabilityPartnerRepository,
            IGenericRepository<tbl_Form> formRepository,
            IGenericRepository<tbl_Module> moduleRepository,
            IGenericRepository<tbl_CustomerContact> customerContactRepository,
            IGenericRepository<tbl_CustomerContactVisa> customerContactVisaRepository,
            IGenericRepository<tbl_UpdateHistory> updateHistoryRepository,
            IBaseRepository baseRepository)
            : base(baseRepository)
        {
            this._dictionaryRepository = dictionaryRepository;
            this._servicesPartnerRepository = servicesPartnerRepository;
            this._tourRepository = tourRepository;
            this._reviewTourRepository = reviewTourRepository;
            this._reviewTourDetailRepository = reviewTourDetailRepository;
            this._customerRepository = customerRepository;
            this._customerVisaRepository = customerVisaRepository;
            this._tagsRepository = tagsRepository;
            this._taskRepository = taskRepository;
            this._documentFileRepository = documentFileRepository;
            this._appointmentHistoryRepository = appointmentHistoryRepository;
            this._contactHistoryRepository = contactHistoryRepository;
            this._contractRepository = contractRepository;
            this._partnerRepository = partnerRepository;
            this._tourGuideRepository = tourGuideRepository;
            this._tourScheduleRepository = tourScheduleRepository;
            this._tourCustomerRepository = tourCustomerRepository;
            this._tourCustomerVisaRepository = tourCustomerVisaRepository;
            this._tourOptionRepository = tourOptionRepository;
            this._staffRepository = staffRepository;
            this._liabilityCustomerRepository = liabilityCustomerRepository;
            this._liabilityPartnerRepository = liabilityPartnerRepository;
            this._formRepository = formRepository;
            this._moduleRepository = moduleRepository;
            this._customerContactRepository = customerContactRepository;
            this._customerContactVisaRepository = customerContactVisaRepository;
            this._updateHistoryRepository = updateHistoryRepository;
            _db = new DataContext();
        }
        #endregion

        #region Permission

        int SDBID = 6;
        int maPB = 0, maNKD = 0, maNV = 0, maCN = 0;
        void Permission(int PermissionsId, int formId)
        {
            var list = _db.tbl_ActionData.Where(p => p.FormId == formId && p.PermissionsId == PermissionsId).Select(p => p.FunctionId).ToList();

            var ltAccess = _db.tbl_AccessData.Where(p => p.PermissionId == PermissionsId && p.FormId == formId).Select(p => p.ShowDataById).FirstOrDefault();
            if (ltAccess != 0)
                this.SDBID = ltAccess;

            switch (SDBID)
            {
                case 2: maPB = clsPermission.GetUser().DepartmentID;
                    maCN = clsPermission.GetUser().BranchID;
                    break;
                case 3: maNKD = clsPermission.GetUser().GroupID;
                    maCN = clsPermission.GetUser().BranchID; break;
                case 4: maNV = clsPermission.GetUser().StaffID; break;
                case 5: maCN = clsPermission.GetUser().BranchID; break;
            }
        }

        #endregion

        #region List

        public ActionResult Index()
        {
            Permission(clsPermission.GetUser().PermissionID, 1120);
            return View();
        }

        [ChildActionOnly]
        public ActionResult _Partial_ListHistory()
        {
            Permission(clsPermission.GetUser().PermissionID, 1120);
            var model = _updateHistoryRepository.GetAllAsQueryable().AsEnumerable()
                .Where(p => p.IsDelete == false)
                    .OrderByDescending(p => p.CreatedDate)
                    .Select(p => new HistoryLogViewModel()
                    {
                        Id = p.Id,
                        Staff = _staffRepository.FindId(p.StaffId).FullName,
                        Date = string.Format("{0:dd-MM-yyyy hh:mm tt}", p.CreatedDate),
                        Note = p.Note,
                        StaffId = p.StaffId,
                        Form = p.FormId != null ? _formRepository.FindId(p.FormId).Name : "",
                        Module = p.ModuleId != null ? _moduleRepository.FindId(p.ModuleId).Name : ""
                    }).ToList();
            return PartialView("_Partial_ListHistory", model);
        }

        public ActionResult FilterDate(DateTime start, DateTime end, int staff)
        {
            Permission(clsPermission.GetUser().PermissionID, 1120);
            var model = _updateHistoryRepository.GetAllAsQueryable().AsEnumerable()
                            .Where(p => p.IsDelete == false
                                && (start == end ? p.CreatedDate.ToString("dd-MM-yyyy") == start.ToString("dd-MM-yyyy") : start <= p.CreatedDate && p.CreatedDate <= end)
                                && p.StaffId == (staff == 0 ? p.StaffId : staff))
                            .OrderByDescending(p => p.CreatedDate)
                            .Select(p => new HistoryLogViewModel()
                            {
                                Id = p.Id,
                                Staff = _staffRepository.FindId(p.StaffId).FullName,
                                Date = string.Format("{0:dd-MM-yyyy hh:mm tt}", p.CreatedDate),
                                Note = p.Note,
                                StaffId = p.StaffId,
                                Form = p.FormId != null ? _formRepository.FindId(p.FormId).Name : "",
                                Module = p.ModuleId != null ? _moduleRepository.FindId(p.ModuleId).Name : ""
                            }).ToList();

VIETLIKE/Views/HistoryLogReport/Index.cshtml
@using CRM.Core
@using VIETLIKE.Utilities
@{
    ViewBag.Title = "Nhật ký hệ thống";
    int i = 0;
}

<div class="page-content">
    <!-- BEGIN PAGE HEAD-->
    <div class="page-head">
        <!-- BEGIN PAGE TITLE -->
        <div class="page-title">
            <h1>NHẬT KÝ HỆ THỐNG</h1>
        </div>
        <!-- END PAGE TITLE -->

    </div>
    <!-- END PAGE HEAD-->
    <!-- BEGIN PAGE BREADCRUMB -->
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="/">Trang chủ</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">Page Layouts</span>
        </li>
    </ul>
    <!-- END PAGE BREADCRUMB -->
    <div class="note note-info">
        @using (Html.BeginForm("ExportExcel", "HistoryLogReport", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="row">
                <div class="col-md-3">
                    <label>Kỳ báo cáo</label>
                    <select class="form-control" id="ddlKyBaoCao" style="width: 100%" name="kybaocao">
                        @foreach (var item in LoadData.KyBaoCaoList())
                        {
                            <option value="@i">@item</option>
                            i++;
                        }
                    </select>
                </div>
                <div id="startEndDate">
                    @{
                        DateTime dateFrom = DateTime.Now.AddYears(-2);
                        DateTime dateTo = new DateTime(DateTime.Now.Year, 12, 31);
                    }
                    <div class="col-md-3">
                        <label>Từ ngày</label>
                        <input type="date" id="txtStartDate" value="@dateFrom.ToString("yyyy-MM-dd")" class="form-control" name="tungay" required />
                    </div>
                    <div class="col-md-3">
                        <label>Đến ngày</label>
                        <input type="date" id="txtEndDate" value="@dateTo.ToString("yyyy-MM-dd")" class=" form-control" name="denngay" required />
                    </div>
                </div>
                <div class="col-md-3">
                    <label>Nhân viên</label>
                    <select class="form-control" id="ddlNhanVien" style="width: 100%" name="nhanvien">
                        <option value="0">-- Tất cả --</option>
                        @foreach (var item in LoadData.StaffList())
                        {
                            <option value="@item.Id">@item.FullName</option>
                            i++;
                        }
                    </select>
                </div>
                <div class="col-md-12" style="margin-top: 10px">
                    <a class="btn btn-default" href="@Url.Action("Index", "HistoryLogReport")"><i class="fa fa-refresh"></i>&nbsp;Nạp</a>
                    <button class="btn btn-success" type="button" id="btnSearch"><i class="fa fa-search"></i>&nbsp;Tìm</button>
                    <button class="btn btn-primary" type="submit" id="export"><i class="icon-action-undo"></i>&nbsp;Export</button>
                    <button class="btn btn-danger" type="button" id="btnRemove"><i class="fa fa-remove"></i>&nbsp;Xóa</button>
                    <a href="#modal-choose-time" class="btn btn-danger" data-toggle="modal"><i class="fa fa-remove"></i>&nbsp;Xóa theo thời gian</a>
                    <input type="hidden" id="listItemId" name="listItemId" />
                </div>
            </div>
        }
    </div>
    <!-- BEGIN PAGE BASE CONTENT -->
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-list-alt font-red"></i>
                        <span class="caption-subject bold uppercase font-red">Nhật ký hệ thống</span>
                    </div>
                </div>
                <div class="portlet-body" id="data-tour">
                    @Html.Action("_Partial_ListHistory", "HistoryLogReport")
                </div>
            </div>
        </div>
    </div>
    <!-- END PAGE BASE CONTENT -->
</div>

@Html.Partial("_Partial_ChooseTime")

@section scripts{
    <script src="~/Scripts/controller/reportlog.js"></script>
    <script>
        $("#ddlBaoCao").select2();
        ////////// kỳ báo cáo
        $("#ddlBaoCao").change(function () {
            var dataPost = {
                id: $("#ddlBaoCao").val()
            };
            $.ajax({
                type: "POST",
                url: '/HistoryLogReport/GetStartEndDate',
                data: JSON.stringify(dataPost),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    $("#tungaydenngay").html(data);
                }
            });
        })
    </script>
}

VIETLIKE/Views/HistoryLogReport/_Partial_ChooseTime.cshtml
@using CRM.Core
@using VIETLIKE.Models
@using VIETLIKE.Utilities
@{
    int i = 0;
}

<div class="modal fade" id="modal-choose-time" role="document" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Chọn thời gian để xóa</h4>
            </div>
            @using (Html.BeginForm("DeleteTime", "HistoryLogReport"))
            {
                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Kỳ báo cáo</label>
                                    <div class="col-lg-10 col-md-10">
                                        <select class="form-control" id="ddlBaoCao" style="width: 100%" name="kybaocao">
                                            @foreach (var item in LoadData.KyBaoCaoList())
                                            {
                                                <option value="@i">@item</option>
                                                i++;
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div id="tungaydenngay">
                                    @{
                                            DateTime dateFrom = DateTime.Now.AddYears(-2);
                                            DateTime dateTo = new DateTime(DateTime.Now.Year, 12, 31);
                                    }
                                    <div class="form-group">
                                        <label class="control-label col-lg-2 col-md-2">Từ ngày</label>
                                        <div class="col-lg-10 col-md-10">
                                            <input type="date" id="txtTuNgay" value="@dateFrom.ToString("yyyy-MM-dd")" class="form-control" name="tungay" required />
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-lg-2 col-md-2">Đến ngày</label>
                                        <div class="col-lg-10 col-md-10">
                                            <input type="date" id="txtDenNgay" value="@dateTo.ToString("yyyy-MM-dd")" class=" form-control" name="denngay" required />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div align="center" style="margin-bottom: 20px">
                    <button type="submit" class="btn blue" id="btnXoa">Xóa</button>
                    <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
                </div>
            }
        </div>
    </div>
</div>

VIETLIKE/Views/HistoryLogReport/_Partial_ListHistory.cshtml
@model IEnumerable<VIETLIKE.Models.HistoryLogViewModel>
@{
    int i = 1;
}

<div class="table-scrollable table-custom-format" id="tableDictionary-Wrapper">
    <table class="table table-bordered table-hover dataTable" id="tableDictionary">
        <thead>
            <tr>
                <td class="width24"></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <th class="table-checkbox">
                    <input type="checkbox" id="allcb" name="allcb" onclick="SelectAllCb()" />
                </th>
                <th>STT</th>
                <th>Module</th>
                <th>Form</th>
                <th>Ngày xử lý</th>
                <th>Diễn giải</th>
                <th>Nhân viên</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() > 0)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td class="width24">
                            <input type="checkbox" value="@item.Id" id="cb@(item.Id)" class="cbItem" name="cb" onclick="CheckSelect()" />
                        </td>
                        <td style="text-align: center">@i</td>
                        <td>@item.Module</td>
                        <td>@item.Form</td>
                        <td>@item.Date</td>
                        <td>@item.Note</td>
                        <td>@item.Staff</td>
                    </tr>
                    i++;
                }
            }
        </tbody>
    </table>
</div>