VIETLIKE/Controllers/Ticket/TicketManageController.cs
using CRM.Core;
using CRM.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using VIETLIKE.Models;
using VIETLIKE.Utilities;

namespace VIETLIKE.Controllers.Ticket
{
    [Authorize]
    public class TicketManageController : BaseController
    {
        // GET: TicketManage

        #region Init

        private IGenericRepository<tbl_Dictionary> _dictionaryRepository;
        private IGenericRepository<tbl_Customer> _customerRepository;
        private IGenericRepository<tbl_Staff> _staffRepository;
        private IGenericRepository<tbl_Tour> _tourRepository;
        private IGenericRepository<tbl_Contract> _contractRepository;
        private IGenericRepository<tbl_Ticket> _ticketRepository;
        private DataContext _db;

        public TicketManageController(IGenericRepository<tbl_Dictionary> dictionaryRepository,
            IGenericRepository<tbl_Customer> customerRepository,
            IGenericRepository<tbl_Staff> staffRepository,
            IGenericRepository<tbl_Tour> tourRepository,
            IGenericRepository<tbl_Contract> contractRepository,
            IGenericRepository<tbl_Ticket> ticketRepository,
            IBaseRepository baseRepository)
            : base(baseRepository)
        {
            this._dictionaryRepository = dictionaryRepository;
            this._customerRepository = customerRepository;
            this._staffRepository = staffRepository;
            this._tourRepository = tourRepository;
            this._contractRepository = contractRepository;
            this._ticketRepository = ticketRepository;
            _db = new DataContext();
        }

        #endregion

        #region List

        int SDBID = 6;
        int maPB = 0, maNKD = 0, maNV = 0, maCN = 0;
        void Permission(int PermissionsId, int formId)
        {
            var list = _db.tbl_ActionData.Where(p => p.FormId == formId && p.PermissionsId == PermissionsId).Select(p => p.FunctionId).ToList();
            ViewBag.IsAdd = list.Contains(1);
            ViewBag.IsDelete = list.Contains(2);
            ViewBag.IsEdit = list.Contains(3);

            //cập nhật trạng thái
            var listUS = _db.tbl_ActionData.Where(p => p.FormId == 1098 & p.PermissionsId == PermissionsId).Select(p => p.FunctionId).ToList();
            ViewBag.IsUpdateStatus = list.Contains(1);

            var ltAccess = _db.tbl_AccessData.Where(p => p.PermissionId == PermissionsId && p.FormId == formId).Select(p => p.ShowDataById).FirstOrDefault();
            if (ltAccess != 0)
                this.SDBID = ltAccess;

            switch (SDBID)
            {
                case 2:
                    maPB = clsPermission.GetUser().DepartmentID;
                    maCN = clsPermission.GetUser().BranchID;
                    break;
                case 3:
                    maNKD = clsPermission.GetUser().GroupID;
                    maCN = clsPermission.GetUser().BranchID; break;
                case 4: maNV = clsPermission.GetUser().StaffID; break;
                case 5: maCN = clsPermission.GetUser().BranchID; break;
            }
        }

        public ActionResult Index()
        {
            Permission(clsPermission.GetUser().PermissionID, 1098);

            if (SDBID == 6)
                return View(new List<tbl_Ticket>());

            var model = _ticketRepository.GetAllAsQueryable().Where(p => (p.Staff == maNV | maNV == 0)
                    & (p.tbl_Staff.DepartmentId == maPB | maPB == 0)
                    & (p.tbl_Staff.StaffGroupId == maNKD | maNKD == 0)
                    & (p.tbl_Staff.HeadquarterId == maCN | maCN == 0) & (p.IsDelete == false))
                    .OrderByDescending(p => p.CreateDate)
                    .ToList();
            return View(model);
        }

        [HttpPost]
        public ActionResult GetIdTicket(int id)
        {
            Session["idTicket"] = id;
            return Json(JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Create

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Create(tbl_Ticket model)
        {
            try
            {
                Permission(clsPermission.GetUser().PermissionID, 1098);
                var checkcode = _ticketRepository.GetAllAsQueryable().FirstOrDefault(p => p.Code == model.Code && p.IsDelete == false);
                if (checkcode == null)
                {
                    model.CreateDate = DateTime.Now;
                    model.ModifyDate = DateTime.Now;
                    model.IsDelete = false;
                    model.Staff = clsPermission.GetUser().StaffID;
                    if (model.CustomerId != null)
                    {
                        model.Name = _customerRepository.FindId(model.CustomerId).FullName;
                    }
                    if (await _ticketRepository.Create(model))
                    {
                        UpdateHistory.SaveHistory(1098, "Thêm mới vé, code: " + model.Code + " - " + model.Name,
                            null, //appointment
                            model.ContractId, //contract
                            model.CustomerId, //customer
                            null, //partner
                            model.ProgramId, //program
                            null, //task
                            model.TourId, //tour
                            null, //quotation
                            null, //document
                            null, //history
                            model.Id // ticket
                        );
                    }
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        #endregion

        #region Update

        public async Task<ActionResult> EditInfoTicket(int id)
        {
            var model = await _ticketRepository.GetById(id);
            return PartialView("_Partial_EditTicket", model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Update(tbl_Ticket model)
        {
            try
            {
                Permission(clsPermission.GetUser().PermissionID, 1098);
                model.ModifyDate = DateTime.Now;
                model.Staff = clsPermission.GetUser().StaffID;
                if (model.CustomerId != null)
                {
                    model.Name = _customerRepository.FindId(model.CustomerId).FullName;
                }
                if (await _ticketRepository.Update(model))
                {
                    UpdateHistory.SaveHistory(1098, "Cập nhật vé: " + model.Code,
                        null, //appointment
                            model.ContractId, //contract
                            model.CustomerId, //customer
                            null, //partner
                            model.ProgramId, //program
                            null, //task
                            model.TourId, //tour
                            null, //quotation
                            null, //document
                            null, //history
                            model.Id // ticket
                            );
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        #endregion

        #region Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(FormCollection fc)
        {
            Permission(clsPermission.GetUser().PermissionID, 1098);
            try
            {
                if (fc["listItemId"] != null && fc["listItemId"] != "")
                {
                    var listIds = fc["listItemId"].Split(',');
                    listIds = listIds.Take(listIds.Count() - 1).ToArray();
                    if (listIds.Count() > 0)
                    {
                        //
                        foreach (var i in listIds)
                        {
                            var item = _ticketRepository.FindId(Convert.ToInt32(i));
                            UpdateHistory.SaveHistory(1098, "Xóa code vé: " + item.Code + " - " + item.Name,
                                null, //appointment
                                item.ContractId, //contract
                                item.CustomerId, //customer
                                null, //partner
                                item.ProgramId, //program
                                null, //task
                                item.TourId, //tour
                                null, //quotation
                                null, //document
                                null, //history
                                item.Id // ticket
                                );
                        }
                        //
                        if (await _ticketRepository.DeleteMany(listIds, false))
                        {
                            return Json(1, JsonRequestBehavior.AllowGet);
                        }
                        else
                        {
                            return Json(0, JsonRequestBehavior.AllowGet);
                        }
                    }
                }
                return Json(0, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }
        #endregion

        #region Other Tab
        public ActionResult _Partial_TabInfoTicket()
        {
            return PartialView("_Partial_TabInfoTicket");
        }

        public ActionResult InfoNote(int id)
        {
            var model = _ticketRepository.FindId(id);

VIETLIKE/Views/TicketManage/Index.cshtml
@using CRM.Core
@model IEnumerable<tbl_Ticket>

@{
    ViewBag.Title = "Quản lý Code vé";
}

<div class="page-content">
    <!-- BEGIN PAGE HEAD-->
    <div class="page-head">
        <!-- BEGIN PAGE TITLE -->
        <div class="page-title">
            <h1>DANH SÁCH CODE VÉ</h1>
        </div>
        <!-- END PAGE TITLE -->
    </div>
    <!-- END PAGE HEAD-->
    <!-- BEGIN PAGE BREADCRUMB -->
    <ul class="page-breadcrumb breadcrumb">
        <li>
            <a href="/">Trang chủ</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span class="active">Page Layouts</span>
        </li>
    </ul>
    <!-- END PAGE BREADCRUMB -->
    <!-- BEGIN PAGE BASE CONTENT -->
    <div class="note note-info">
        <div class="row">
            <div class="col-md-12">
                <a href="@Url.Action("Index", "TicketManage")" class="btn btn-default"><i class="fa fa-refresh"></i>&nbsp;Nạp</a>
                @if (ViewBag.IsAdd != null && ViewBag.IsAdd)
                {
                    <button class="btn btn-primary" id="btnAdd" href="#modal-insert-ticket" data-toggle="modal"><i class="fa fa-plus"></i>&nbsp;Thêm</button>
                }
                @if (ViewBag.IsEdit != null && ViewBag.IsEdit)
                {
                    <button class="btn btn-warning" id="btnEdit"><i class="fa fa-pencil"></i>&nbsp;Sửa</button>
                }
                @if (ViewBag.IsDelete != null && ViewBag.IsDelete)
                {
                    <button class="btn btn-danger" id="btnRemove"><i class="fa fa-remove"></i>&nbsp;Xóa</button>
                    <form action="@Url.Action("Delete", "TicketManage")" method="post" style="position:absolute">
                        @Html.AntiForgeryToken()
                        <input type="hidden" id="listItemId" name="listItemId" />
                    </form>
                }
                <button type="button" class="btn btn-success" data-toggle="collapse" data-target="#demo"><i class="icon-book-open"></i>&nbsp;Ẩn/Hiện cột</button>
            </div>
        </div>
    </div>
    <div class="row collapse" id="demo">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="portlet light bordered">
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-md-2 col-xs-2 col-sm-2">
                            <ul>
                                <li><a class="toggle-vis" data-column="1" style="color: #333; font-weight: bold">Code vé</a></li>
                                <li><a class="toggle-vis" data-column="2" style="color: #333; font-weight: bold">Loại vé</a></li>
                            </ul>
                        </div>
                        <div class="col-md-2 col-xs-2 col-sm-2">
                            <ul>
                                <li><a class="toggle-vis" data-column="3" style="color: #333; font-weight: bold">Tình trạng</a></li>
                                <li><a class="toggle-vis" data-column="4" style="color: #333; font-weight: bold">Tên</a></li>
                            </ul>
                        </div>
                        <div class="col-md-2 col-xs-2 col-sm-2">
                            <ul>
                                <li><a class="toggle-vis" data-column="5" style="color: #333; font-weight: bold">Số điện thoại</a></li>
                                <li><a class="toggle-vis" data-column="6" style="color: #333; font-weight: bold">Chi phí</a></li>
                            </ul>
                        </div>
                        <div class="col-md-2 col-xs-2 col-sm-2">
                            <ul>
                                <li><a class="toggle-vis" data-column="7" style="color: #333; font-weight: bold">Điểm đi</a></li>
                                <li><a class="toggle-vis" data-column="8" style="color: #333; font-weight: bold">Điểm đến</a></li>
                            </ul>
                        </div>
                        <div class="col-md-2 col-xs-2 col-sm-2">
                            <ul>
                                <li><a class="toggle-vis" data-column="9" style="color: #333; font-weight: bold">Ngày đi</a></li>
                                <li><a class="toggle-vis" data-column="10" style="color: #333; font-weight: bold">Ngày về</a></li>
                            </ul>
                        </div>
                        <div class="col-md-2 col-xs-2 col-sm-2">
                            <ul>
                                <li><a class="toggle-vis" data-column="9" style="color: #333; font-weight: bold">Nhân viên nhập</a></li>
                                <li><a class="toggle-vis" data-column="10" style="color: #333; font-weight: bold">Ngày nhập</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="portlet light bordered">
                <div class="portlet-body">
                    <div class="table-responsive table-custom-format" id="tableDictionary-Wrapper">
                        <table class="table table-striped table-bordered table-hover dataTable" id="tableDictionary">
                            <thead>
                                <tr>
                                    <td class="width24"></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <th class="table-checkbox">
                                        <input type="checkbox" id="allcb" name="allcb" onclick="SelectAllCb()" />
                                    </th>
                                    <th>Code vé</th>
                                    <th>Loại vé</th>
                                    <th>Tình trạng</th>
                                    <th>Tên</th>
                                    <th>Số điện thoại</th>
                                    <th>Điểm đi</th>                    
                                    <th>Điểm đến</th>
                                    <th>Ngày đi</th>
                                    <th>Ngày về</th>
                                    <th>Chi phí</th>
                                    <th>Nhân viên nhập</th>
                                    <th>Ngày nhập</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr class="odd gradeX">
                                        <td class="width24">
                                            <input type="checkbox" value="@item.Id" id="cb@(item.Id)" class="cbItem" name="cb" onclick="CheckSelect()" />
                                        </td>
                                        <td>@item.Code</td>
                                        <td>@item.tbl_DictionaryType.Name</td>
                                        <td style="@(item.tbl_DictionaryStatus != null ? "color: #fff; background-color: " + item.tbl_DictionaryStatus.Note + "" : "")">@item.tbl_DictionaryStatus.Name</td>
                                        <td class="textalignleft">@item.Name</td>
                                        <td>@item.Phone</td>
                                        <td class="textalignleft">@item.tbl_TagsStart.Tag</td>
                                        <td class="textalignleft">@item.tbl_TagsEnd.Tag</td>
                                        <td>@(item.StartDate != null ? string.Format("{0:dd-MM-yyyy}", item.StartDate) : "")</td>
                                        <td>@(item.EndDate != null ? string.Format("{0:dd-MM-yyyy}", item.EndDate) : "")</td>
                                        <td>@(item.Price != null ? string.Format("{0:0,0}", item.Price) : "0") @item.tbl_DictionaryCurrency.Name</td>
                                        <td>@item.tbl_Staff.FullName</td>
                                        <td>@string.Format("{0:dd-MM-yyyy}", item.CreateDate)</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="portlet light bordered">
                <div class="portlet-body">
                    <div class="tabbable-custom ">
                        <ul class="nav nav-tabs ">
                            <li class="active">
                                <a href="#tab1" data-toggle="tab">Diễn giải</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab1">
                                @Html.Partial("_Partial_TabInfoTicket", new tbl_Ticket())
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END PAGE BASE CONTENT -->
</div>

@Html.Partial("_Partial_InsertTicket", new tbl_Ticket())
<div id="data-ticket"></div>

@section scripts{
<script src="~/Content/ckeditor-basic/ckeditor.js"></script>
    <script src="~/Scripts/controller/ticket.js"></script>
}

VIETLIKE/Views/TicketManage/_Partial_EditTicket.cshtml
@using CRM.Core
@using VIETLIKE.Utilities
@model tbl_Ticket

<div class="modal fade" id="modal-edit-ticket" role="document" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">Cập nhật code vé</h4>
            </div>
            @using (Html.BeginForm("Update", "TicketManage", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.ContractId)
                @Html.HiddenFor(model => model.CreateDate)
                @Html.HiddenFor(model => model.IsDelete) 
                @Html.HiddenFor(model => model.ProgramId)

                <div class="modal-body">
                    <div class="form-horizontal">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Code vé</label>
                                    <div class="col-lg-10 col-md-10">
                                        @Html.TextBoxFor(model => model.Code, new { @class = "form-control", @required = "required" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Loại vé</label>
                                    <div class="col-lg-4 col-md-4">
                                        <select class="form-control" name="TypeId" id="edit-type" style="width: 100%">
                                            @foreach (var item in LoadData.TicketTypeList())
                                            {
                                                <option value="@item.Id" @(Model.TypeId != null && Model.TypeId == item.Id ? "selected" : "")>@item.Name</option>
                                            }
                                        </select>
                                    </div>
                                    <label class="control-label col-lg-2 col-md-2">Tình trạng</label>
                                    <div class="col-lg-4 col-md-4">
                                        <select class="form-control" name="StatusId" id="edit-status" style="width: 100%">
                                            @foreach (var item in LoadData.TicketStatusList())
                                            {
                                                <option value="@item.Id" @(Model.StatusId != null && Model.StatusId == item.Id ? "selected" : "")>@item.Name</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Điểm đi</label>
                                    <div class="col-lg-4 col-md-4">
                                        <select class="form-control" name="StartPlace" id="edit-start" style="width: 100%">
                                            @foreach (var item in LoadData.TinhThanhQuocGia())
                                            {
                                                <option value="@item.Id" @(Model.StartPlace != null && Model.StartPlace == item.Id ? "selected" : "")>@item.Tags</option>
                                            }
                                        </select>
                                    </div>
                                    <label class="control-label col-lg-2 col-md-2">Điểm đến</label>
                                    <div class="col-lg-4 col-md-4">
                                        <select class="form-control" name="EndPlace" id="edit-end" style="width: 100%">
                                            @foreach (var item in LoadData.TinhThanhQuocGia())
                                            {
                                                <option value="@item.Id" @(Model.EndPlace != null && Model.EndPlace == item.Id ? "selected" : "")>@item.Tags</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Ngày đi</label>
                                    <div class="col-lg-4 col-md-4">
                                        @Html.TextBoxFor(model => model.StartDate, "{0:yyyy-MM-dd}", new { @type = "date", @class = "form-control" })
                                    </div>
                                    <label class="control-label col-lg-2 col-md-2">Ngày về</label>
                                    <div class="col-lg-4 col-md-4">
                                        @Html.TextBoxFor(model => model.EndDate, "{0:yyyy-MM-dd}", new { @type = "date", @class = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Chi phí</label>
                                    <div class="col-lg-7 col-md-7">
                                        @Html.TextBoxFor(model => model.Price, new { @class = "form-control" })
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <select class="form-control" name="CurrencyId" id="edit-currency" style="width: 100%">
                                            @foreach (var item in LoadData.CurrencyList())
                                            {
                                                <option value="@item.Id" @(Model.CurrencyId != null && Model.CurrencyId == item.Id ? "selected" : "")>@item.Name</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Khách hàng</label>
                                    <div class="col-lg-4 col-md-4">
                                        <select class="form-control" name="CustomerId" id="edit-customer" style="width: 100%">
                                            @foreach (var item in LoadData.CustomerList())
                                            {
                                                <option value="@item.Id" @(Model.CustomerId != null && Model.CustomerId == item.Id ? "selected" : "")>@item.FullName</option>
                                            }
                                        </select>
                                    </div>
                                    <label class="control-label col-lg-2 col-md-2">Điện thoại</label>
                                    <div class="col-lg-4 col-md-4">
                                        @Html.TextBoxFor(model => model.Phone, new { @class = "form-control", id = "edit-phone" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-lg-2 col-md-2">Diễn giải</label>
                                    <div class="col-lg-10 col-md-10">
                                        @Html.TextAreaFor(model => model.Note, new { @class = "form-control", id = "edit-note" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div align="center" style="margin-bottom: 20px">
                    <button type="submit" class="btn blue" id="btnLuuSua">Lưu</button>
                    <button type="button" class="btn default" data-dismiss="modal">Đóng</button>
                </div>
            }
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

VIETLIKE/Views/TicketManage/_Partial_TabInfoTicket.cshtml
@using CRM.Core
@model tbl_Ticket

<div>
    @Html.Raw(Model.Note)
</div>